# Generated by Django 4.1.7 on 2023-06-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rankdarbiai', '0002_rename_bio_userprofile_biography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_products',
            field=models.ManyToManyField(blank=True, related_name='users', to='Rankdarbiai.product'),
        ),
    ]
