# Generated by Django 4.1.7 on 2023-06-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rankdarbiai', '0003_userprofile_user_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
