# Generated by Django 4.1.7 on 2023-06-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rankdarbiai', '0007_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
